id: P010800
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25503
  title: སྟག་འབུམ་རྒྱལ་གྱི་སྒྲུང་གཏམ་ལ་དཔྱད་པ།
  author: ''
  volumes:
    1e059757065a4e56873af5e4b01641dd:
      image_group_id: I1KG25505
      title: ''
      volume_number: 1
      total_pages: 262
