id: I00CB1E41
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T03:17:11+00:00'
last_modified: '2022-06-08T17:37:06.776087+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25503
  title: སྟག་འབུམ་རྒྱལ་གྱི་སྒྲུང་གཏམ་ལ་དཔྱད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4F11:
      image_group_id: I1KG25505
      title: ''
      total_pages: 262
      order: 1
      base_file: 4F11.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
